In [123]:
import numpy as np

# print out version number to ensure proper installation
print(np.__version__)

1.19.2


In [20]:
# Create python list
x = [1,2,3,4,5,6]

# Convert list variable to numpy array
x = np.array(x)
print(x, '\n')

# Observe same behavior when feeding entire list into numpy array
y = np.array([1,2,3,4,5,6])
print(y, '\n')

# Create two dimensional array
z = np.array([(1,2,3), (4,5,6)])
print(z, '\n')

[1 2 3 4 5 6] 

[1 2 3 4 5 6] 

[[1 2 3]
 [4 5 6]] 



In [62]:
# print the shape (dimension sizes) of the numpy array
print(z.shape, '\n')

# print the type of variables stored within the numpy array
print(z.dtype, '\n')

(2, 3) 

int32 



In [61]:
# Resize the numpy array to be two dimensional
x_reshape = x.reshape(3,2)
print(x_reshape, '\n')

# Swap numpy array rows and columns
x_T = x_reshape.T
print(x_T, '\n')

# Reshape with -1 to allow dimension to automatically fit to data size
x_reshape2 = x.reshape(-1,1)
print(x_reshape2, '\n')

[[1 2]
 [3 4]
 [5 6]] 

[[1 3 5]
 [2 4 6]] 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] 



In [63]:
# Initialize numpy array of shape 2,3 with zeros
zeros = np.zeros((2,3))
print(zeros, '\n')

# Initialize numpy array of same shape as zeros array with ones
ones = np.ones(zeros.shape)
print(ones, '\n')

# Initialize numpy array of same shape as zeros array with fives
fives = np.ones(zeros.shape)*5
print(fives, '\n')

[[0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]] 

[[5. 5. 5.]
 [5. 5. 5.]] 



In [66]:
# Initialize array with zeros as type integer
ones = np.ones(zeros.shape, dtype=np.int32)
print(ones, '\n')

# Convert fives array to dtype integer by recasting to numpy array
dtype1 = np.array(fives, dtype=np.int32)
print(dtype1, '\n')

# Convert fives array to dtype integer by assigning dtype
dtype2 = fives.astype(np.int32)
print(dtype2, '\n')

# Convert fives array to dtype float by assigning dtype
dtype3 = ones.astype(np.float64)
print(dtype3, '\n')

[[1 1 1]
 [1 1 1]] 

[[5 5 5]
 [5 5 5]] 

[[5 5 5]
 [5 5 5]] 

[[1. 1. 1.]
 [1. 1. 1.]] 



In [69]:
# Initialize array with random values from 0 to 1
random = np.random.random(ones.shape)
print(random, '\n')

# Initialize array with random integers from 0 to 255
randint = np.random.randint(0,255,ones.shape)
print(randint, '\n')

# Initialize array with values from 0 to 10 evenly spaced to total 101 values
linspace = np.linspace(0,10,101)
print(linspace, '\n')

[[0.56415364 0.66253138 0.89325524]
 [0.21691071 0.82079071 0.24878636]] 

[[208 205 206]
 [ 61  73 151]] 

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10. ] 



In [76]:
# Define two arrays with random values 
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])

# Perform math operations on entire arrays to store results as a new array
c = a+b
d = a-b
e = a*b
f = a/b
g = a**b
h = a @ b # Dot product of two arrays. Alternate: a.dot(b)
i = a*5

# Print math outputs 
print(c, '\n')
print(d, '\n')
print(e, '\n')
print(f, '\n')
print(g, '\n')
print(h, '\n')
print(i, '\n')

[6 6 6 6 6] 

[-4 -2  0  2  4] 

[5 8 9 8 5] 

[0.2 0.5 1.  2.  5. ] 

[ 1 16 27 16  5] 

35 

[ 5 10 15 20 25] 



In [83]:
# Define array of random values
a = np.array([-1,2,-5,6,-7])

# Use numpy built in math functions on arrays to return new array of values
b = np.abs(a)
c = np.sin(a)
d = np.cos(a)
e = np.exp(a)
f = np.sqrt(b)

# Print math outputs
print(b, '\n')
print(c, '\n')
print(d, '\n')
print(e, '\n')
print(f, '\n')

[1 2 5 6 7] 

[-0.84147098  0.90929743  0.95892427 -0.2794155  -0.6569866 ] 

[ 0.54030231 -0.41614684  0.28366219  0.96017029  0.75390225] 

[3.67879441e-01 7.38905610e+00 6.73794700e-03 4.03428793e+02
 9.11881966e-04] 

[1.         1.41421356 2.23606798 2.44948974 2.64575131] 



In [124]:
# Define array of random values
a = np.array([-1,2,-5,6,-7])

# Use built in numpy math summary functions or arrays
print(a.min(), '\n')
print(a.max(), '\n')
print(a.mean(), '\n')
print(a.std(), '\n')
print(a.sum(), '\n')
print(a.cumsum(), '\n')

-7 

6 

-1.0 

4.69041575982343 

-5 

[-1  1 -4  2 -5] 



In [85]:
# Define multi-dimensional array of random values 
a = np.array([(1,2,3,4), (4,2,5,7), (3,5,7,2)])

# Print original array
print(a, '\n')

# Print sum of dim=0 (columns)
print(a.sum(axis=0), '\n')

# Print sum of dim=1 (rows)
print(a.sum(axis=1), '\n')

[[1 2 3 4]
 [4 2 5 7]
 [3 5 7 2]] 

[ 8  9 15 13] 

[10 18 17] 



In [126]:
# Define multi-dimensional array of random values 
a = np.array([(1,2,3,4), (4,2,5,7), (3,5,7,2)])

# Print array at different indices 
print(a, '\n')
print(a[0], '\n')
print(a[-1], '\n')

# Use comma to reference multiple dimensions
print(a[:,0], '\n')

# Use condition to filter array where condition is true 
print(a[a>2], '\n')

# Use where to return indices where condition is true in array
print(np.where(a>2))

[[1 2 3 4]
 [4 2 5 7]
 [3 5 7 2]] 

[1 2 3 4] 

[3 5 7 2] 

[1 4 3] 

[3 4 4 5 7 3 5 7] 

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64), array([2, 3, 0, 2, 3, 0, 1, 2], dtype=int64))


In [129]:
# Define multi-dimensional array of random values
random = np.random.random((3,4))
print(random, '\n')

# Use clip to bound data or lower and upper values 
random = random.clip(.25,.75)
print(random)

[[0.70007263 0.7775183  0.42565316 0.25693048]
 [0.70274932 0.72035078 0.41881751 0.11116223]
 [0.27645505 0.71903009 0.41254158 0.57002923]] 

[[0.70007263 0.75       0.42565316 0.25693048]
 [0.70274932 0.72035078 0.41881751 0.25      ]
 [0.27645505 0.71903009 0.41254158 0.57002923]]


In [131]:
# Define array of random values with Not a Number (nan) and Infinite (inf) values
a = np.array([(1,2,np.nan,4), (4,2,5,np.nan), (3,np.inf,7,2)])
print(a, '\n')

# Convert nan values and infinite values to predefined values
b = np.nan_to_num(a, 0, posinf=10, neginf=-10)
print(b, '\n')

[[ 1.  2. nan  4.]
 [ 4.  2.  5. nan]
 [ 3. inf  7.  2.]] 

[[ 1.  2.  0.  4.]
 [ 4.  2.  5.  0.]
 [ 3. 10.  7.  2.]] 

